version: '3.5'

services:
  # Delta API
  delta:
    image: delta
    build:
      context: .
    container_name: delta_radius
    tty: true
    working_dir: /var/www
    networks:
      - net

  # Delta Nginx
  nginx:
    image: nginx:alpine
    container_name: delta_nginx_radius
    hostname: api
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./config/conf.d:/etc/nginx/conf.d
    networks:
      - net

networks:
  net:
    driver: bridge